# Generated by Django 5.1 on 2024-09-28 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="picture",
            field=models.ImageField(blank=True, null=True, upload_to="review_images/"),
        ),
    ]
