# Generated by Django 5.1.1 on 2024-10-07 17:03

import review.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("review", "0002_review_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="review",
            name="rating",
            field=models.IntegerField(validators=[review.models.validate_positive]),
        ),
    ]
