# Generated by Django 5.1 on 2024-09-28 07:03

import book.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0002_book_cover_page"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="author_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="book",
            name="publication_date",
            field=models.DateField(validators=[book.models.validate_year]),
        ),
    ]
