# Generated by Django 5.1.1 on 2024-10-07 17:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("book", "0003_book_author_name_alter_book_publication_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="publication_date",
            field=models.DateField(),
        ),
    ]
