# Generated by Django 5.1.1 on 2024-10-07 17:03

import movies.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Movies",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(max_length=255)),
                ("Director", models.CharField(max_length=500)),
                (
                    "Release_date",
                    models.DateField(),
                ),
                ("Genre", models.CharField(max_length=100)),
                ("Description", models.CharField(max_length=300)),
                (
                    "Poster",
                    models.ImageField(blank=True, null=True, upload_to="movie_poster/"),
                ),
            ],
        ),
    ]
