# Generated by Django 5.1.1 on 2024-10-08 02:00

import movies.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0002_rename_movies_movie"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="Release_date",
            field=models.DateField(),
        ),
    ]
