# Generated by Django 5.1.1 on 2024-10-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0003_alter_movie_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="Release_date",
            field=models.DateField(),
        ),
    ]
