# Generated by Django 5.1.1 on 2024-10-08 05:15

import movies.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0004_alter_movie_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="Poster",
            field=models.ImageField(blank=True, upload_to="movie_poster/"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="Release_date",
            field=models.DateField(),
        ),
    ]
