# Generated by Django 5.1.1 on 2024-10-12 06:45

import movies.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0005_alter_movie_poster_alter_movie_release_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="Genre",
            field=models.CharField(
                choices=[
                    ("AC", "Action"),
                    ("DR", "Drama"),
                    ("CO", "Comedy"),
                    ("HO", "Horror"),
                    ("RO", "Romance"),
                    ("SF", "Science Fiction"),
                    ("FA", "Fantasy"),
                    ("DO", "Documentary"),
                    ("TH", "Thriller"),
                ],
                default="AC",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="Poster",
            field=models.ImageField(blank=True, null=True, upload_to="movie_poster/"),
        ),
        migrations.AlterField(
            model_name="movie",
            name="Release_date",
            field=models.DateField(),
        ),
    ]
