# Generated by Django 5.1.1 on 2024-10-12 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0006_alter_movie_genre_alter_movie_poster_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="Description",
            field=models.TextField(max_length=300),
        ),
    ]
