# Generated by Django 5.1.1 on 2024-10-12 07:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0007_alter_movie_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="Genre",
            field=models.CharField(
                choices=[
                    ("AC", "Action"),
                    ("DR", "Drama"),
                    ("CO", "Comedy"),
                    ("HO", "Horror"),
                    ("RO", "Romance"),
                    ("SF", "Science Fiction"),
                    ("FA", "Fantasy"),
                    ("DO", "Documentary"),
                    ("TH", "Thriller"),
                    ("ACC", "Action comedy"),
                    ("ACH", "Action horror"),
                    ("HT", "Horror thriller"),
                    ("AT", "Action thriller"),
                    ("W", "Western"),
                ],
                default="AC",
                max_length=4,
            ),
        ),
    ]
